#!/usr/bin/env bash
# File: build.sh

OUTPUT="mpv-music"
VERSION="0.21.0"

echo "Building mpv-music (v$VERSION)..."

# write header
cat <<HEADER > "$OUTPUT"
#!/usr/bin/env bash
# Purpose: MPV wrapper for music playback
VERSION="$VERSION"
# Auto-generated by build.sh. DO NOT EDIT THIS FILE DIRECTLY.

set -euo pipefail
HEADER

# concatenate Modules (Order is very very critical!)
cat src/01_vars.sh \
    src/02_utils.sh \
    src/03_config.sh \
    src/04_metadata.sh \
    src/05_ui.sh \
    src/06_main.sh >> "$OUTPUT"

# make executable
chmod +x "$OUTPUT"

echo "Build complete: ./$OUTPUT"
